import React, { Fragment } from 'react';
import { ReactNavbar } from "overlay-navbar";
const options = {
  // burgerColorHover: "#eb4034",
  // logo,
  // logoWidth: "20vmax",
  // navColor1: "white",
  // logoHoverSize: "10px",
  // logoHoverColor: "#eb4034",
  // link1Text: "Home",
  // link2Text: "Products",
  // link3Text: "Contact",
  // link4Text: "About",
  // link1Url: "/",
  // link2Url: "/products",
  // link3Url: "/contact",
  // link4Url: "/about",
  // link1Size: "1.3vmax",
  // link1Color: "rgba(35, 35, 35,0.8)",
  // nav1justifyContent: "flex-end",
  // nav2justifyContent: "flex-end",
  // nav3justifyContent: "flex-start",
  // nav4justifyContent: "flex-start",
  // link1ColorHover: "#eb4034",
  // link1Margin: "1vmax",
  // profileIconUrl: "/login",
  // profileIconColor: "rgba(35, 35, 35,0.8)",
  // searchIconColor: "rgba(35, 35, 35,0.8)",
  // cartIconColor: "rgba(35, 35, 35,0.8)",
  // profileIconColorHover: "#eb4034",
  // searchIconColorHover: "#eb4034",
  // cartIconColorHover: "#eb4034",
  // cartIconMargin: "1vmax",
  logo: "https://www.lunapic.com/editor/premade/transparent.gif",
  burgerColor: "crimson",
  navColor1: "#fff5f5",
  burgerColorHover: "#900",
  logoWidth: "50%",
  logoHoverColor: "crimson",
  link1Size: "1.2rem",
  link1Color: "#121212",
  link1Padding: "1vmax",
  link1ColorHover: "crimson",
  nav2justifyContent: "flex-end",
  link1Margin: "1vmax",
  link2Margin: "0",
  link3Margin: "0",
  link4Margin: "1vmax",
  nav3justifyContent: "flex-start",
  link1Text: "Home",
  link1Family: "sans-serif",
  link2Text: "Products",
  link3Text: "About Us",
  link4Text: "Contact Us",
  link1Url: "/",
  link2Url: "/products",
  link3Url: "/about",
  link4Url: "/contact",
  nav4justifyContent: "flex-start",
  profileIconUrl: "/login",
  searchIconMargin: "0.5vmax",
  cartIconMargin: "1vmax",
  profileIconMargin: "0.5vmax",
  searchIconColor: "#121212",
  cartIconColor: "#121212",
  profileIconColor: "#121212",
  searchIconColorHover: "crimson",
  cartIconColorHover: "crimson",
  profileIconColorHover: "crimson",
};
const Header = () => {
  return (
    <Fragment>
      <header>
        <ReactNavbar {...options} />
      </header>
    </Fragment>
  )
}

export default Header